### ISSUE TITLE
task file to watch and gen

### ISSUE THREAD

**Issue by joeblew999** [romshark/toki#7]
hey, 

basic task file for working with toki with the gen command in watch mode.

you can add this to the repo if you think it helps.

it works for me on windows and darwin and linux.

If your many folders down, this task file will run and jump down to your {{.USER_WORKING_DIR}}. so it's great for many projects with examples etc.

```yaml

# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['dev.env', '{{.ENV}}/.env', '{{.HOME}}/.env']


tasks:
  default:
    cmds:
      - task --list-all

  install:
    desc: install the toki cli.
    cmds:
      # just install it to get going.
      - go install -v github.com/romshark/toki@latest

### help

  run:help:
    desc: help cli.
    cmds:
      - toki -h


### init 

  run:init:new:
    desc: create new example
    cmds:
      # hardcoded for now.
      - cd {{.USER_WORKING_DIR}} && mkdir -p tokiexample && cd tokiexample
      
      - cd {{.USER_WORKING_DIR}}/tokiexample && go mod init tokiexample
      - cd {{.USER_WORKING_DIR}}/tokiexample && go mod tidy

      # in case your in a mono repo.
      - cd {{.USER_WORKING_DIR}}/tokiexample && touch go.work && go work use .
      - cd {{.USER_WORKING_DIR}}/tokiexample && go work use .

  run:init:del:
    cmds:
      - rm -rf tokiexample

  run:init:template:
    desc: copies our example main.go into the example, to get going
    cmds:
      #- cd {{.USER_WORKING_DIR}} && cp main-template.go {{.USER_WORKING_DIR}}/tokiexample/main.go
      - cd {{.USER_WORKING_DIR}} && cp main-template-basic.go {{.USER_WORKING_DIR}}/tokiexample/main.go

### gen from inside any golang project.

  run:gen:help:
    desc: gen help
    cmds:
      - cd {{.USER_WORKING_DIR}} && toki generate -h

  run:gen:default:
    desc: gen default language bundle in watch mode.
    watch: true
    sources: 
      - '**/*main.go'
    generates:
      - 'tokibundle/**/*'
    cmds:
      # Our default locale is en.
      - cd {{.USER_WORKING_DIR}} && toki generate -l en
      - cd {{.USER_WORKING_DIR}} && go mod tidy
    verbose: true

  run:gen:all:
    desc: gen other language bundles
    cmds:
      # generate the other langs we use.
      # NOT possible yet with TOKI: 
      - cd {{.USER_WORKING_DIR}} && toki generate de
      - cd {{.USER_WORKING_DIR}} && go mod tidy

### lint 
  run:lint:default:
    desc: lint default language bundle
    cmds:
      - cd {{.USER_WORKING_DIR}} && toki lint -l en
    
```
